version: '3.8'

services:

  nginx:
    build: nginx
    container_name: nginx
    expose:
      - 80
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      flask:
        condition: service_healthy
    networks:
      - network

  flask:
    build: backend
    restart: always
    container_name: flask
    command: python wsgi.py
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@bank_db_container:5432/${DATABASE_NAME}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - UPLOAD_PATH=${UPLOAD_PATH}
    expose:
      - 9000
    networks:
      - network
    depends_on:
      bank_db_container:
        condition: service_healthy
    volumes:
      - backend:/srv/${UPLOAD_PATH}
    healthcheck:
      test: wget --spider http://localhost:9000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5


  bank_db_container:
    image: postgres:16.0-alpine
    container_name: bank-db-container
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db_new:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - network
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_new:
    driver: local
  backend:
    driver: local


networks:
  network:
    driver: bridge

